model:
  modes1: [15, 12, 9, 9, 9]
  modes2: [15, 12, 9, 9, 9]
  width: 64
  fc_dim: 128
  layers: [16, 24, 24, 32, 32]
  in_dim: 3
  out_dim: 1
  act: 'gelu'
  upsample_factor: [2, 2]

data:
  dataset: 'NavierStokes2D'
  data_path: "/home/dsw/ocean_lzh/ocean_sr/NavierStokes_V1e-5_N1200_T20.mat"
  sample_factor: [2, 2]
  train_batchsize: 256
  eval_batchsize: 256
  train_ratio: 0.979
  valid_ratio: 0.001
  test_ratio: 0.02
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'

train:
  model_name: 'FNO2d'
  random_seed: 42
  cuda: True
  device: 0
  epochs: 400
  patience: 10
  eval_freq: 5
  saving_best: True
  saving_checkpoint: True
  checkpoint_freq: 20
  resume_path: ~
  visualize: True
  visual_interval: 1
  model_type: 'neural_operator'  # 'neural_operator' or 'diffusion'
  distributed: True


optimize:
  optimizer: 'AdamW'
  lr: 0.0001
  weight_decay: 0.001

schedule:
  scheduler: 'StepLR'
  step_size: 100
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: True
  wandb_project: 'FNO2d-NavierStokes2D'
