model:
  in_channels: 3
  out_channels: 1
  input_size: 32
  output_size: 64
  hidden_dim: 128
  k: 6
  n_layers: 6
  c: 1
  alpha: 2
  L: 0
  base: 'legendre'
  act: 'gelu'

data:
  dataset: 'NavierStokes2D'
  data_path: "/home/yc/CVPR_26_fluid_SR/DiffSR-main-master/NavierStokes_V1e-5_N1200_T20.mat"
  sample_factor: [2, 2]
  train_batchsize: 128
  eval_batchsize: 128
  train_ratio: 0.08
  valid_ratio: 0.01
  test_ratio: 0.01
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'

train:
  model_name: 'MWT'
  random_seed: 42
  cuda: True
  device: 0
  epochs: 5
  patience: 10
  eval_freq: 5
  saving_best: True
  saving_checkpoint: False
  checkpoint_freq: 100
  resume_path: ~
  visualize: False
  num_visuals: 20
  model_type: 'neural_operator'
  distributed: True

optimize:
  optimizer: 'AdamW'
  lr: 0.001
  weight_decay: 0.001

schedule:
  scheduler: 'StepLR'
  step_size: 300
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: False
  wandb_project: ''
