
model:
  which_model_G: ddpm  # ddpm, sr3
  finetune_norm: false
  unet:
    in_channel: 4
    out_channel: 1
    inner_channel: 32
    channel_multiplier: [1, 2, 4, 8]
    attn_res: [0]
    res_blocks: 1
    dropout: 0.2
    norm_groups: 32
  beta_schedule:
    train:
      schedule: linear
      n_timestep: 100
      linear_start: 1.0e-4
      linear_end: 2.0e-2
    val:
      schedule: linear
      n_timestep: 100
      linear_start: 1.0e-4
      linear_end: 2.0e-2
  diffusion:
    image_size: 64  # image size
    channels: 1  # sample channel
    conditional: True

data:
  dataset: 'NavierStokes2D'
  data_path: "C:/Users/jjj/Desktop/program/code/diffsr_DDP_DDPM/NavierStokes_V1e-5_N1200_T20.mat"
  downsample_factor: 4
  train_batchsize: 8
  eval_batchsize: 1
  train_ratio: 0.08
  valid_ratio: 0.001
  test_ratio: 0.001
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'

train:
  random_seed: 42
  cuda: True
  device: 0
  epochs: 20
  patience: 2
  eval_freq: 1
  saving_best: True
  saving_checkpoint: True
  checkpoint_freq: 1
  model_type: 'diffusion'  # 'neural_operator' or 'diffusion' or "transformer"
  phase: 'train'  
  model_name: 'DDPM'
  visualize: True
  num_visuals: 20
  resume_path: "/home/dsw/ocean_lzh/ocean_sr/diffsr/logs/NavierStokes2D/20251001_033124_DDPM/checkpoint/checkpoint_epoch_0.pth"

optimize:
  optimizer: 'AdamW'
  lr: 0.0001
  weight_decay: 0.001

schedule:
  scheduler: 'StepLR'
  step_size: 300
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: False
  wandb_project: ''
