
model:
  which_model_G: sr3  # ddpm, sr3
  finetune_norm: false
  unet:
    in_channel: 2
    out_channel: 1
    inner_channel: 32
    channel_multiplier: [1, 2, 4, 8]
    attn_res: [0]
    res_blocks: 1
    dropout: 0.2
    norm_groups: 32
  beta_schedule:
    train:
      schedule: linear
      n_timestep: 500
      linear_start: 1.0e-4
      linear_end: 2.0e-2
    val:
      schedule: linear
      n_timestep: 1000
      linear_start: 1.0e-4
      linear_end: 2.0e-2
  diffusion:
    image_size: 64  # image size
    channels: 1  # sample channel
    conditional: True

data:
  dataset: 'NavierStokes2D'
  data_path: "/home/dsw/ocean_lzh/ocean_sr/NavierStokes_V1e-5_N1200_T20.mat"
  sample_factor: [2,2]
  train_batchsize: 128
  eval_batchsize: 1
  train_ratio: 0.08
  valid_ratio: 0.001
  test_ratio: 0.001
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'

train:
  random_seed: 42
  cuda: True
  device: 0
  epochs: 20
  patience: 2
  eval_freq: 2
  saving_best: True
  saving_checkpoint: True
  checkpoint_freq: 1
  model_type: 'diffusion'  # 'neural_operator' or 'diffusion' or "transformer"
  phase: 'train'  
  model_name: 'SR3'
  visualize: True
  visual_interval: 1
  num_visuals: 10
  resume_path: "/home/dsw/ocean_lzh/ocean_sr/diffsr/logs/NavierStokes2D/20251001_033124_DDPM/checkpoint/checkpoint_epoch_0.pth"

optimize:
  optimizer: 'AdamW'
  lr: 0.0001
  weight_decay: 0.001

schedule:
  scheduler: 'StepLR'
  step_size: 300
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: True
  wandb_project: 'SR3'
