model:
  input_channels: 1
  output_channels: 1
  use_coord_input: True
  width: 256
  blocks: 16
  upscale: 2

  encoder_config:
    n_resblocks: 16
    n_feats: 64
    res_scale: 1.0
    scale: 2
    no_upsampling: True
    input_channels: 1
    output_channels: 64


data:
  dataset: 'NavierStokes2D'
  data_path: "/home/yc/CVPR_26_fluid_SR/DiffSR-main-master1/DiffSR-main-master/NavierStokes_V1e-5_N1200_T20.mat"
  sample_factor: [2, 2]
  train_batchsize: 16
  eval_batchsize: 16
  train_ratio: 0.08
  valid_ratio: 0.01
  test_ratio: 0.01
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'

train:
  model_name: 'SRNO'
  random_seed: 42
  cuda: True
  device: 0
  epochs: 20
  patience: 10
  eval_freq: 5
  saving_best: True
  saving_checkpoint: False
  checkpoint_freq: 100
  resume_path: ~
  visualize: False
  num_visuals: 20
  model_type: 'neural_operator'
  distributed: True

optimize:
  optimizer: 'AdamW'
  lr: 0.001
  weight_decay: 0.001

schedule:
  scheduler: 'StepLR'
  step_size: 300
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: False
  wandb_project: ''
