model:
  input_resolution: 32
  output_resolution: 64
  in_channels: 3
  out_channels: 1
  n_hidden: 96
  n_layers: 3
  depth: 2
  num_heads: 4
  window_size: 4
  mlp_ratio: 4.
  qkv_bias: True
  # qk_scale: None
  drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.1
  # norm_layer: nn.LayerNorm
  act: 'gelu'

data:
  dataset: 'NavierStokes2D'
  data_path: "/home/yc/CVPR_26_fluid_SR/DiffSR-main-master1/DiffSR-main-master/NavierStokes_V1e-5_N1200_T20.mat"
  sample_factor: [2, 2]
  train_batchsize: 16
  eval_batchsize: 16
  # 改
  train_ratio: 0.08
  valid_ratio: 0.01
  test_ratio: 0.01
  subset: False
  subset_ratio: 0.1
  normalize: True
  normalizer_type: 'PGN'

train:
  model_name: 'Swin_Transformer'
  random_seed: 42
  cuda: True
  device: 0
  epochs: 20
  patience: 10
  eval_freq: 5
  saving_best: True
  saving_checkpoint: True
  checkpoint_freq: 100
  resume_path: ~
  visualize: True
  visual_interval: 1
  model_type: 'neural_operator'  # 'neural_operator' or 'diffusion'
  distributed: True

optimize:
  optimizer: 'AdamW'
  lr: 0.002
  weight_decay: 0.001

schedule:
  scheduler: 'StepLR'
  step_size: 300
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: True
  wandb_project: 'Swin_Transformer-NavierStokes2D'
